baseURL = "https://fikriazh.my.id/"
title = "Mahasemesta"

[permalinks]
  'post' = '/:title/'

[markup.goldmark.renderer]
unsafe = true

[params]
keywords = "mahasemesta, blog, semesta, oracle"
description = "Personal blog about my universe"
author = "Fikri Azhar Novianto"

stylesheets = ["critical-styles.css", "font.css", "style.css"]

[params.assets]
css = ["css/fonts.css"]

[[params.nav.custom]]
title = "On Duty"
url = "/onduty/"

[[params.nav.custom]]
title = "About"
url = "/about/"