baseURL = "https://semestaku.my.id/"
title = "Mahasemesta"
copyright = "©2022 Mahasemesta"

enableRobotsTXT = true
summaryLength = 15

# paginate = 5

# Google Analytics
#googleAnalytics = "UA-123-45"

[markup.goldmark.renderer]
unsafe = true

[mediaTypes]
[mediaTypes."text/toml"]
suffixes = ["toml"]

[outputFormats]
[outputFormats.TOML]
mediaType = "text/toml"

[outputs]
  home = ["HTML", "TOML"]

[params]
style = "dark"
#logo = ""
#slogan = ""
keywords = "mahasemesta, blog, semesta, oracle"
description = "Personal blog about my universe"
author = "Fikri Azhar Novianto"

[params.assets]
css = ["css/fonts.css"]

[[params.nav.custom]]
title = "Oracle"
url = "/oracle/"

[[params.nav.custom]]
title = "About"
url = "/about/"