baseURL = "https://semestaku.my.id/"
title = "Mahasemesta"

disableKinds = ["RSS", "taxonomy", "taxonomyTerm", "robotsTXT"]
enableEmoji = true

[markup.goldmark.renderer]
unsafe = true

[params]
keywords = "mahasemesta, blog, semesta, oracle"
description = "Personal blog about my universe"
author = "Fikri Azhar Novianto"

[[params.menu]]
title = "On Duty"
url = "/onduty/"

[[params.menu]]
title = "About"
url = "/about/"

[sitemap]
  changefreq = ''
  filename = 'sitemap.xml'
  priority = 0.5

[[redirects]]
    from   = "/**"
    to     = "/404.html"
    status = 404

[markup.highlight]
codeFences = true
guessSyntax = true
noClasses = true
style = "monokai"