baseURL = "https://fikriazh.my.id/"
title = "Mahasemesta"

enableRobotsTXT = true
# summaryLength = 10
paginate = 5

# Google Analytics
#googleAnalytics = "UA-123-45"

[permalinks]
  'post' = '/:title/'

[markup.goldmark.renderer]
unsafe = true

[params]
style = "dark"
keywords = "mahasemesta, blog, semesta, oracle"
description = "Personal blog about my universe"
author = "Fikri Azhar Novianto"

[params.assets]
css = ["css/fonts.css"]

[[params.nav.custom]]
title = "On Duty"
url = "/onduty/"

[[params.nav.custom]]
title = "About"
url = "/about/"