baseURL = "https://semestaku.my.id/"
title = "Mahasemesta"

disableKinds = ["taxonomy", "taxonomyTerm"]
enableEmoji = true
enableRobotsTXT = true
disqusShortname = 'semestaku-my-id'

[markup.goldmark.renderer]
unsafe = true

[params]
keywords = "mahasemesta, semesta, oracle, spiritual"
description = "Personal blog about my universe"
author = "Fikri Azhar Novianto"

[[params.menu]]
title = "Blog"
url = "/blog/"
ico = "📖"

[[params.menu]]
title = "On Duty"
url = "/onduty/"
ico = "⚒"

[[params.menu]]
title = "About"
url = "/about/"
ico = "🙊"

[sitemap]
  changefreq = ''
  filename = 'sitemap.xml'
  priority = 0.5

[[redirects]]
    from   = "/**"
    to     = "/404.html"
    status = 404

[markup.highlight]
codeFences = true
guessSyntax = true
noClasses = true
style = "monokai"